trigger:
- master

variables:
 
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'npm install'

- script: npm build
displayName: 'npm build'

- task: ArchiveFiles@2
displayName: 'Archive files'
inputs:
  rootFolderOrFile: '$(Build.SourcesDirectory)/code/function'
  includeRootFolder: false
  archiveType: 'zip'
  archiveFile: '$(Build.SourcesDirectory)/drop.zip'
  replaceExistingArchive: true

- task: CopyFiles@2
  displayName: 'Copy ARM templates'
  inputs:
    contents: 'drop.zip'
    sourceFolder: '$(Build.SourcesDirectory)'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true
    overWrite: true

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'drop' 
    targetPath: '$(Build.ArtifactStagingDirectory)'

